// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4FPmu2gePlstNv0KaREt99G83hrawt5Y',
    appId: '1:132718616613:web:9d1a9b0266504dd5989fcc',
    messagingSenderId: '132718616613',
    projectId: 'jadwallab-350e4',
    authDomain: 'jadwallab-350e4.firebaseapp.com',
    storageBucket: 'jadwallab-350e4.firebasestorage.app',
    measurementId: 'G-TNL4PKJ58S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg8D6fD-gPdDDOwem9Ge8qgvQ7kFrcOTY',
    appId: '1:132718616613:android:55254ece335c67c0989fcc',
    messagingSenderId: '132718616613',
    projectId: 'jadwallab-350e4',
    storageBucket: 'jadwallab-350e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0wFbyEpTb1YzArgof2cikefHuryKZXp4',
    appId: '1:132718616613:ios:3388863b482b19ea989fcc',
    messagingSenderId: '132718616613',
    projectId: 'jadwallab-350e4',
    storageBucket: 'jadwallab-350e4.firebasestorage.app',
    iosBundleId: 'com.example.jadwalLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0wFbyEpTb1YzArgof2cikefHuryKZXp4',
    appId: '1:132718616613:ios:3388863b482b19ea989fcc',
    messagingSenderId: '132718616613',
    projectId: 'jadwallab-350e4',
    storageBucket: 'jadwallab-350e4.firebasestorage.app',
    iosBundleId: 'com.example.jadwalLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4FPmu2gePlstNv0KaREt99G83hrawt5Y',
    appId: '1:132718616613:web:177081c58af0985e989fcc',
    messagingSenderId: '132718616613',
    projectId: 'jadwallab-350e4',
    authDomain: 'jadwallab-350e4.firebaseapp.com',
    storageBucket: 'jadwallab-350e4.firebasestorage.app',
    measurementId: 'G-K24E2LJT2X',
  );
}
